KLineStyles = [
    {"name": "2crows", "CDL": "CDL_2CROWS", "name_zh": "两只乌鸦"},
    {"name": "3blackcrows", "CDL": "CDL_3BLACKCROWS", "name_zh": "三只乌鸦"},
    {"name": "3inside", "CDL": "CDL_3INSIDE", "name_zh": "三个内部向上/向下"},
    {"name": "3linestrike", "CDL": "CDL_3LINESTRIKE", "name_zh": "三线打击"},
    {"name": "3outside", "CDL": "CDL_3OUTSIDE", "name_zh": "三外部上涨和下跌"},
    {"name": "3starsinsouth", "CDL": "CDL_3STARSINSOUTH", "name_zh": "南方三星"},
    {"name": "3whitesoldiers", "CDL": "CDL_3WHITESOLDIERS", "name_zh": "三个白兵"},
    {"name": "abandonedbaby", "CDL": "CDL_ABANDONEDBABY", "name_zh": "弃婴"},
    {"name": "advanceblock", "CDL": "CDL_ADVANCEBLOCK", "name_zh": "上升乏力"},
    {"name": "belthold", "CDL": "CDL_BELTHOLD", "name_zh": "捉腰带线"},
    {"name": "breakaway", "CDL": "CDL_BREAKAWAY", "name_zh": "脱离"},
    {"name": "closingmarubozu", "CDL": "CDL_CLOSINGMARUBOZU", "name_zh": "收盘缺影线"},
    {"name": "concealbabyswall", "CDL": "CDL_CONCEALBABYSWALL", "name_zh": "藏婴吞没"},
    {"name": "counterattack", "CDL": "CDL_COUNTERATTACK", "name_zh": "反击线"},
    {"name": "darkcloudcover", "CDL": "CDL_DARKCLOUDCOVER", "name_zh": "乌云压顶"},
    {"name": "doji", "CDL": "CDL_DOJI", "name_zh": "十字"},
    {"name": "dojistar", "CDL": "CDL_DOJISTAR", "name_zh": "十字星"},
    {"name": "dragonflydoji", "CDL": "CDL_DRAGONFLYDOJI", "name_zh": "蜻蜓十字/T形十字"},
    {"name": "engulfing", "CDL": "CDL_ENGULFING", "name_zh": "吞噬模式"},
    {"name": "eveningdojistar", "CDL": "CDL_EVENINGDOJISTAR", "name_zh": "十字暮星"},
    {"name": "eveningstar", "CDL": "CDL_EVENINGSTAR", "name_zh": "暮星"},
    {"name": "gapsidesidewhite", "CDL": "CDL_GAPSIDESIDEWHITE", "name_zh": "向上/下跳空并列阳线"},
    {"name": "gravestonedoji", "CDL": "CDL_GRAVESTONEDOJI", "name_zh": "墓碑十字/倒T十字"},
    {"name": "hammer", "CDL": "CDL_HAMMER", "name_zh": "锤头"},
    {"name": "hangingman", "CDL": "CDL_HANGINGMAN", "name_zh": "上吊线"},
    {"name": "harami", "CDL": "CDL_HARAMI", "name_zh": "母子线"},
    {"name": "haramicross", "CDL": "CDL_HARAMICROSS", "name_zh": "十字孕线"},
    {"name": "highwave", "CDL": "CDL_HIGHWAVE", "name_zh": "风高浪大线"},
    {"name": "hikkake", "CDL": "CDL_HIKKAKE", "name_zh": "陷阱"},
    {"name": "hikkakemod", "CDL": "CDL_HIKKAKEMOD", "name_zh": "修正陷阱"},
    {"name": "homingpigeon", "CDL": "CDL_HOMINGPIGEON", "name_zh": "家鸽"},
    {"name": "identical3crows", "CDL": "CDL_IDENTICAL3CROWS", "name_zh": "三胞胎乌鸦"},
    {"name": "inneck", "CDL": "CDL_INNECK", "name_zh": "颈内线"},
    {"name": "invertedhammer", "CDL": "CDL_INVERTEDHAMMER", "name_zh": "倒锤头"},
    {"name": "kicking", "CDL": "CDL_KICKING", "name_zh": "反冲形态"},
    {"name": "kickingbylength", "CDL": "CDL_KICKINGBYLENGTH","name_zh": "由较长缺影线决定的反冲形态"},
    {"name": "ladderbottom", "CDL": "CDL_LADDERBOTTOM", "name_zh": "梯底"},
    {"name": "longleggeddoji", "CDL": "CDL_LONGLEGGEDDOJI", "name_zh": "长脚十字"},
    {"name": "longline", "CDL": "CDL_LONGLINE", "name_zh": "长蜡烛"},
    {"name": "marubozu", "CDL": "CDL_MARUBOZU", "name_zh": "光头光脚/缺影线"},
    {"name": "matchinglow", "CDL": "CDL_MATCHINGLOW", "name_zh": "相同低价"},
    {"name": "mathold", "CDL": "CDL_MATHOLD", "name_zh": "铺垫"},
    {"name": "morningdojistar", "CDL": "CDL_MORNINGDOJISTAR", "name_zh": "十字晨星"},
    {"name": "morningstar", "CDL": "CDL_MORNINGSTAR", "name_zh": "晨星"},
    {"name": "onneck", "CDL": "CDL_ONNECK", "name_zh": "颈上线"},
    {"name": "piercing", "CDL": "CDL_PIERCING", "name_zh": "刺透形态"},
    {"name": "rickshawman", "CDL": "CDL_RICKSHAWMAN", "name_zh": "黄包车夫"},
    {"name": "risefall3methods", "CDL": "CDL_RISEFALL3METHODS", "name_zh": "上升/下降三法"},
    {"name": "separatinglines", "CDL": "CDL_SEPARATINGLINES", "name_zh": "分离线"},
    {"name": "shootingstar", "CDL": "CDL_SHOOTINGSTAR", "name_zh": "射击之星"},
    {"name": "shortline", "CDL": "CDL_SHORTLINE", "name_zh": "短蜡烛"},
    {"name": "spinningtop", "CDL": "CDL_SPINNINGTOP", "name_zh": "纺锤"},
    {"name": "stalledpattern", "CDL": "CDL_STALLEDPATTERN", "name_zh": "停顿形态"},
    {"name": "sticksandwich", "CDL": "CDL_STICKSANDWICH", "name_zh": "条形三明治"},
    {"name": "takuri", "CDL": "CDL_TAKURI", "name_zh": "蜻蜓爪(下影很长蜻蜓爪)"},
    {"name": "tasukigap", "CDL": "CDL_TASUKIGAP", "name_zh": "跳空并列阴阳线"},
    {"name": "thrusting", "CDL": "CDL_THRUSTING", "name_zh": "插入"},
    {"name": "tristar", "CDL": "CDL_TRISTAR", "name_zh": "三星"},
    {"name": "unique3river", "CDL": "CDL_UNIQUE3RIVER", "name_zh": "奇特三河床"},
    {"name": "upsidegap2crows", "CDL": "CDL_UPSIDEGAP2CROWS", "name_zh": "向上跳空的两只乌鸦"},
    {"name": "xsidegap3methods", "CDL": "CDL_XSIDEGAP3METHODS", "name_zh": "上升/下降跳空三法"}
]

KLineStyles_names =[style['name'] for style in KLineStyles]
KLineStyles_cdls =[style['CDL'] for style in KLineStyles]
KLineStyles_names_zh =[style['name_zh'] for style in KLineStyles]

def add_cdl_pattern(df):
    df.ta.cdl_pattern(name=KLineStyles_names, append=True)
    df.rename(columns={"CDL_DOJI_10_0.1":"CDL_DOJI"},inplace=True)
